version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: url-shortener-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=url_shortener
    volumes:
      - mongodb_data:/data/db
    networks:
      - url-shortener-network
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - url-shortener-network
    restart: unless-stopped

  url-shortener-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017
      - DATABASE_NAME=url_shortener
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - url-shortener-network

volumes:
  mongodb_data:
  redis_data:

networks:
  url-shortener-network:
    driver: bridge
